"""add config field to tenant

Revision ID: 991b15609084
Revises: d84d888ccc59
Create Date: 2025-10-10 22:01:38.798799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991b15609084'
down_revision = 'd84d888ccc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
