"""init schema

Revision ID: d84d888ccc59
Revises: 
Create Date: 2025-10-09 23:15:57.543510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84d888ccc59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('permanent_code', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_corp_id'), ['corp_id'], unique=True)

    op.create_table('card_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_json', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'userid', name='uq_tenant_userid')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_userid'), ['userid'], unique=False)

    op.create_table('card_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_logs_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('md5', sa.String(length=64), nullable=True),
    sa.Column('bucket', sa.String(length=128), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_md5'), ['md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_file_assets_md5'))

    op.drop_table('file_assets')
    with op.batch_alter_table('card_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_card_logs_member_id'))
        batch_op.drop_index(batch_op.f('ix_card_logs_event'))
        batch_op.drop_index(batch_op.f('ix_card_logs_created_at'))

    op.drop_table('card_logs')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_userid'))
        batch_op.drop_index(batch_op.f('ix_members_tenant_id'))

    op.drop_table('members')
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_templates_tenant_id'))

    op.drop_table('card_templates')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_corp_id'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
